<?php

// autoload-classmap.php @generated by Mozart

$srcstrauss = dirname(__FILE__);

return array(
   'BH_WC_Gateway_Load_Balancer\Pablo_Pacheco\WP_Namespace_Autoloader\WP_Namespace_Autoloader' => $srcstrauss . '/pablo-sg-pacheco/wp-namespace-autoloader/src/WP_Namespace_Autoloader.php',
   'BH_WC_Gateway_Load_Balancer\Katzgrau\KLogger\Logger' => $srcstrauss . '/katzgrau/klogger/src/Logger.php',
   'BH_WC_Gateway_Load_Balancer\WPTRT\AdminNotices\Notices' => $srcstrauss . '/wptrt/admin-notices/src/Notices.php',
   'BH_WC_Gateway_Load_Balancer\WPTRT\AdminNotices\Dismiss' => $srcstrauss . '/wptrt/admin-notices/src/Dismiss.php',
   'BH_WC_Gateway_Load_Balancer\WPTRT\AdminNotices\Notice' => $srcstrauss . '/wptrt/admin-notices/src/Notice.php',
   'BH_WC_Gateway_Load_Balancer\Spatie\Backtrace\Backtrace' => $srcstrauss . '/spatie/backtrace/src/Backtrace.php',
   'BH_WC_Gateway_Load_Balancer\Spatie\Backtrace\File' => $srcstrauss . '/spatie/backtrace/src/File.php',
   'BH_WC_Gateway_Load_Balancer\Spatie\Backtrace\CodeSnippet' => $srcstrauss . '/spatie/backtrace/src/CodeSnippet.php',
   'BH_WC_Gateway_Load_Balancer\Spatie\Backtrace\Frame' => $srcstrauss . '/spatie/backtrace/src/Frame.php',
   'BH_WC_Gateway_Load_Balancer\Psr\Log\LoggerAwareInterface' => $srcstrauss . '/psr/log/Psr/Log/LoggerAwareInterface.php',
   'BH_WC_Gateway_Load_Balancer\Psr\Log\LogLevel' => $srcstrauss . '/psr/log/Psr/Log/LogLevel.php',
   'BH_WC_Gateway_Load_Balancer\Psr\Log\Test\LoggerInterfaceTest' => $srcstrauss . '/psr/log/Psr/Log/Test/LoggerInterfaceTest.php',
   'BH_WC_Gateway_Load_Balancer\Psr\Log\Test\TestLogger' => $srcstrauss . '/psr/log/Psr/Log/Test/TestLogger.php',
   'BH_WC_Gateway_Load_Balancer\Psr\Log\Test\DummyTest' => $srcstrauss . '/psr/log/Psr/Log/Test/DummyTest.php',
   'BH_WC_Gateway_Load_Balancer\Psr\Log\LoggerAwareTrait' => $srcstrauss . '/psr/log/Psr/Log/LoggerAwareTrait.php',
   'BH_WC_Gateway_Load_Balancer\Psr\Log\InvalidArgumentException' => $srcstrauss . '/psr/log/Psr/Log/InvalidArgumentException.php',
   'BH_WC_Gateway_Load_Balancer\Psr\Log\NullLogger' => $srcstrauss . '/psr/log/Psr/Log/NullLogger.php',
   'BH_WC_Gateway_Load_Balancer\Psr\Log\LoggerInterface' => $srcstrauss . '/psr/log/Psr/Log/LoggerInterface.php',
   'BH_WC_Gateway_Load_Balancer\Psr\Log\LoggerTrait' => $srcstrauss . '/psr/log/Psr/Log/LoggerTrait.php',
   'BH_WC_Gateway_Load_Balancer\Psr\Log\AbstractLogger' => $srcstrauss . '/psr/log/Psr/Log/AbstractLogger.php',
);