name: Run PHP CodeSniffer

# Run PHPCBF to fix changes then PHPCS report
#
# NB: Pull requests from forks do not have access to repository secrets so cannot commit changes.
#
# @author BrianHenryIE

on:
  push:
    branches:
      - master

jobs:
  php-codesniffer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@2.11.0
        with:
          php-version: ${{ matrix.php }}
          tools: composer, cs2pr

#      - name: Create Composer auth.json
#        run: php -r "file_put_contents( 'auth.json', json_encode( [ 'http-basic' => [ 'blog.brianhenry.ie' => [ 'username' => '"${{ secrets.COMPOSER_AUTH_SECRET }}"', 'password' => 'satispress' ] ] ] ) );"

      - name: Run Composer install
        uses: php-actions/composer@v1

      - name: Run PHPCBF to fix what it can
        continue-on-error: true
        run: vendor/bin/phpcbf

      - name: Commit PHPCBF changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: "PHPCBF"

      - name: Run PHPCS to add annotations to the commit
        continue-on-error: true
        run: vendor/bin/phpcs -q -n --report=checkstyle | cs2pr
